version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the Angular application..."
      - npm run build -- --configuration=production

artifacts:
  files:
    - '**/*'
  base-directory: 'dist/compass/browser'

